/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DAO.ClienteDAO;
import Modelo.DAO.FacturaDAO;
import Modelo.DAO.LoginDAO;
import Modelo.DAO.VendedorDAO;
import Modelo.FacadeCliente;
import Modelo.FacadeFactura;
import Modelo.FacadeProducto;
import Modelo.FacadeProveedor;
import Modelo.FacadeVendedor;
import Modelo.Vendedor;
import Modelo.Producto;
import Modelo.Provedor;
import Modelo.cliente;
import Modelo.factura;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian
 */
public class AdminDB1 extends javax.swing.JFrame {

    /**
     * Creates new form VendedorDB
     */
    

    public AdminDB1() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargartabla();
        cargartablaVendedor();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDash = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pndash = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_CorreoRV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_IdentificacionRV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        txt_NombreRv1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pass_RV = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIdentificacionPro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNombrePro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDireccionPro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtContactoPro = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTelefonoPro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNombreProduc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPrecioProduc = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtDimensionProduc = new javax.swing.JTextField();
        txtMaterialProduc = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtColorProduc = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtTipoProduc = new javax.swing.JTextField();
        btnIngresarProductos = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtCantidadpro = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtNumeroRef = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVendedores = new javax.swing.JTable();
        btnEditarVendedor = new javax.swing.JButton();
        pnconfig = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_NombreV = new javax.swing.JTextField();
        Identificacion = new javax.swing.JTextField();
        contraseña_V = new javax.swing.JPasswordField();
        btneditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin ProntoMueble");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 255, 51));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText("Online");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenido ");

        btnDash.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setText("Dashboard");
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashMouseClicked(evt);
            }
        });

        btnConfig.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnConfig.setText("Configuracion");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/datos.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 580));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 730, 40));

        jPanel8.setLayout(new java.awt.CardLayout());

        pndash.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Dashboard");

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 8)); // NOI18N
        jLabel12.setText("version 1.0");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel13.setText("Inicio > Dashboard");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(java.awt.Color.black);
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/idea.png"))); // NOI18N
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        txt_CorreoRV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CorreoRVFocusLost(evt);
            }
        });
        txt_CorreoRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoRVActionPerformed(evt);
            }
        });
        jPanel6.add(txt_CorreoRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, -1));

        jLabel6.setText("Registro vendedores");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel7.setText("Correo");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel14.setText("Clave");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txt_IdentificacionRV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdentificacionRVKeyTyped(evt);
            }
        });
        jPanel6.add(txt_IdentificacionRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

        jLabel17.setText("Identificacion");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btn_registrar.setText("Registrar Venta");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel6.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        labelTotal.setBackground(java.awt.Color.white);
        jPanel6.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, 30));

        txt_NombreRv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreRv1KeyTyped(evt);
            }
        });
        jPanel6.add(txt_NombreRv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, -1));

        jLabel18.setText("Nombre");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        pass_RV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_RVActionPerformed(evt);
            }
        });
        jPanel6.add(pass_RV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));

        jTabbedPane1.addTab("Registrar Vendedor", jPanel6);

        jPanel4.setBackground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Proveedor");

        jLabel16.setText("Numero de identificacion");

        txtIdentificacionPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionProActionPerformed(evt);
            }
        });
        txtIdentificacionPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionProKeyTyped(evt);
            }
        });

        jLabel19.setText("Nombre");

        txtNombrePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProActionPerformed(evt);
            }
        });
        txtNombrePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProKeyTyped(evt);
            }
        });

        jLabel20.setText("Direccion");

        txtDireccionPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProActionPerformed(evt);
            }
        });

        jLabel21.setText("contacto");

        txtContactoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoProActionPerformed(evt);
            }
        });
        txtContactoPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactoProKeyTyped(evt);
            }
        });

        jLabel24.setText("telefono");

        txtTelefonoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProActionPerformed(evt);
            }
        });
        txtTelefonoPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoProKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Producto");

        jLabel28.setText("Nombre");

        txtNombreProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProducActionPerformed(evt);
            }
        });
        txtNombreProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProducKeyTyped(evt);
            }
        });

        jLabel29.setText("Precio");

        txtPrecioProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProducActionPerformed(evt);
            }
        });
        txtPrecioProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProducKeyTyped(evt);
            }
        });

        jLabel30.setText("Dimension");

        txtDimensionProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDimensionProducActionPerformed(evt);
            }
        });

        txtMaterialProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaterialProducActionPerformed(evt);
            }
        });
        txtMaterialProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaterialProducKeyTyped(evt);
            }
        });

        jLabel31.setText("Material");

        jLabel32.setText("color");

        txtColorProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorProducActionPerformed(evt);
            }
        });
        txtColorProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorProducKeyTyped(evt);
            }
        });

        jLabel33.setText("Tipo");

        txtTipoProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoProducActionPerformed(evt);
            }
        });
        txtTipoProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoProducKeyTyped(evt);
            }
        });

        btnIngresarProductos.setText("Aceptar");
        btnIngresarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProductosActionPerformed(evt);
            }
        });

        jLabel27.setText("cantidad del producto");

        txtCantidadpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadproActionPerformed(evt);
            }
        });
        txtCantidadpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadproKeyTyped(evt);
            }
        });

        jLabel34.setText("Numero de referencia");

        txtNumeroRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroRefActionPerformed(evt);
            }
        });
        txtNumeroRef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroRefKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTelefonoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContactoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccionPro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdentificacionPro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel24)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidadpro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtColorProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaterialProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDimensionProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecioProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                    .addComponent(txtNumeroRef, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtIdentificacionPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtNumeroRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtNombreProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtPrecioProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtDimensionProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtMaterialProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtColorProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtTipoProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtDireccionPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtContactoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtTelefonoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtCantidadpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnIngresarProductos)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Provedor", jPanel4);

        jPanel9.setBackground(java.awt.Color.white);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel35.setText("                PRODUCTOS");

        btnEditar.setBackground(new java.awt.Color(204, 204, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 0, 0));
        btnBorrar.setText("Cambiar estado");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnEditar)
                .addGap(144, 144, 144)
                .addComponent(btnBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Ver Productos", jPanel9);

        jPanel10.setBackground(java.awt.Color.white);

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(" Vendedores");

        TablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaVendedores);

        btnEditarVendedor.setText("Editar");
        btnEditarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addGap(110, 110, 110))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarVendedor)
                .addGap(310, 310, 310))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnEditarVendedor)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Ver Vendedores", jPanel10);

        javax.swing.GroupLayout pndashLayout = new javax.swing.GroupLayout(pndash);
        pndash.setLayout(pndashLayout);
        pndashLayout.setHorizontalGroup(
            pndashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pndashLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pndashLayout.setVerticalGroup(
            pndashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(pndash, "card2");

        jLabel22.setText("Nombre");

        jLabel23.setText("Identificacion");

        jLabel25.setText("Contraseña");

        Identificacion.setEnabled(false);

        btneditar.setText("Aceptar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(462, 462, 462))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(40, 40, 40)
                        .addComponent(txt_NombreV)
                        .addGap(460, 460, 460))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneditar)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contraseña_V, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txt_NombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(contraseña_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(btneditar)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnconfigLayout = new javax.swing.GroupLayout(pnconfig);
        pnconfig.setLayout(pnconfigLayout);
        pnconfigLayout.setHorizontalGroup(
            pnconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnconfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnconfigLayout.setVerticalGroup(
            pnconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnconfigLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(pnconfig, "card3");

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 730, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseClicked
        // TODO add your handling code here:
        btnDash.setBackground(new java.awt.Color(44, 59, 66));
        pndash.setVisible(true);

        btnConfig.setBackground(new java.awt.Color(44, 59, 66));
        pnconfig.setVisible(false);


    }//GEN-LAST:event_btnDashMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        // TODO add your handling code here:
        btnDash.setBackground(new java.awt.Color(44, 59, 66));
        pndash.setVisible(false);

        btnConfig.setBackground(new java.awt.Color(44, 59, 66));
        pnconfig.setVisible(true);
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        cambiarEstado();
        cargartabla();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarProducto();
        cargartabla();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNumeroRefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroRefKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroRefKeyTyped

    private void txtNumeroRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroRefActionPerformed

    private void txtCantidadproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadproKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();    // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadproKeyTyped

    private void txtCantidadproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadproActionPerformed

    private void btnIngresarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProductosActionPerformed
        String nombreProv, direcion, contacto, telefono, nombrePro, dimension, material, color, tipo;
        int precio, numeroID, cantidad, numref;
        /////////////provedor
        numeroID=Integer.parseInt(txtIdentificacionPro.getText());
        nombreProv=txtNombrePro.getText();
        direcion=txtDireccionPro.getText();
        contacto=txtContactoPro.getText();
        telefono=txtTelefonoPro.getText();
        Provedor prove= new Provedor(numeroID, nombreProv, direcion, contacto);
        prove.setTelefono(telefono);
        ////////////////producto
        nombrePro=txtNombreProduc.getText();
        precio=Integer.parseInt(txtPrecioProduc.getText());
        dimension=txtDimensionProduc.getText();
        material=txtMaterialProduc.getText();
        color=txtColorProduc.getText();
        tipo=txtTipoProduc.getText();
        cantidad=Integer.parseInt(txtCantidadpro.getText());
        numref=Integer.parseInt(txtNumeroRef.getText());
        Producto pro = new Producto(dimension, numref, precio, nombrePro);
        pro.setID_P(numref);
        pro.setColor(color);
        pro.setTipo(tipo);
        pro.setCantidad(cantidad);
        pro.setMaterial(material);
        pro.setEstado(true);
        //////////////////////////////insercion a la  base de datos

        if(insertarProducto(pro,prove)){
            JOptionPane.showMessageDialog(null, "Datos Ingresados");
            cargartabla();
        }else{
            JOptionPane.showMessageDialog(null, "No se ingresaron los DATOS");
        }
    }//GEN-LAST:event_btnIngresarProductosActionPerformed

    private void txtTipoProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoProducKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProducKeyTyped

    private void txtTipoProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProducActionPerformed

    private void txtColorProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorProducKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorProducKeyTyped

    private void txtColorProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorProducActionPerformed

    private void txtMaterialProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaterialProducKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaterialProducKeyTyped

    private void txtMaterialProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaterialProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaterialProducActionPerformed

    private void txtDimensionProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDimensionProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDimensionProducActionPerformed

    private void txtPrecioProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProducKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProducKeyTyped

    private void txtPrecioProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProducActionPerformed

    private void txtNombreProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProducKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProducKeyTyped

    private void txtNombreProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProducActionPerformed

    private void txtTelefonoProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoProKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProKeyTyped

    private void txtTelefonoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProActionPerformed

    private void txtContactoProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoProKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoProKeyTyped

    private void txtContactoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoProActionPerformed

    private void txtDireccionProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionProActionPerformed

    private void txtNombreProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProKeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProKeyTyped

    private void txtNombreProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProActionPerformed

    private void txtIdentificacionProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionProKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionProKeyTyped

    private void txtIdentificacionProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionProActionPerformed

    private void pass_RVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_RVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_RVActionPerformed

    private void txt_NombreRv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreRv1KeyTyped
        char c = evt.getKeyChar();

        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreRv1KeyTyped

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String nombre, correo, clave;

        int ID = Integer.parseInt(this.txt_IdentificacionRV.getText());
        nombre = txt_NombreRv1.getText();
        correo = txt_CorreoRV.getText();
        clave = pass_RV.getText();

        Vendedor vendedor2 = new Vendedor (ID,nombre);
        vendedor2.setCorreo(correo);
        vendedor2.setClave(clave);
        FacadeVendedor facaV = new FacadeVendedor();

        if(facaV.Crearvendedor(vendedor2)){
            System.out.println(vendedor2.getCorreo());
            LoginDAO obDAO = new LoginDAO();
            obDAO.insertLogin(vendedor2);
        }

    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_IdentificacionRVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdentificacionRVKeyTyped
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_txt_IdentificacionRVKeyTyped

    private void txt_CorreoRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoRVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoRVActionPerformed

    private void txt_CorreoRVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CorreoRVFocusLost
        if(Email(this.txt_CorreoRV.getText())){

        }else{
            JOptionPane.showMessageDialog(null, "Correo incorrecto","Error", JOptionPane.INFORMATION_MESSAGE);
            this.txt_CorreoRV.requestFocus();
        }
    }//GEN-LAST:event_txt_CorreoRVFocusLost

    private void btnEditarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVendedorActionPerformed
        editarVendedor();
    }//GEN-LAST:event_btnEditarVendedorActionPerformed
    
    private void editarProducto(){
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {
            DefaultTableModel tb = (DefaultTableModel) this.tablaProductos.getModel();
            Producto objS= (Producto) tablaProductos.getValueAt(fila, 1);
            EditarProducto ventana = new EditarProducto(this,true,objS);
            ventana.setVisible(true);
            cargartabla();
            
        }
    }
    private void editarVendedor(){
        int fila = TablaVendedores.getSelectedRow();
        if (fila >= 0) {
            DefaultTableModel tb = (DefaultTableModel) this.TablaVendedores.getModel();
            Vendedor objS= (Vendedor) TablaVendedores.getValueAt(fila, 1);
            EditarVendedor ventana = new EditarVendedor(this,objS,true);
            ventana.setVisible(true);
            cargartablaVendedor();
        }
    }
    private void cambiarEstado(){
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {
            DefaultTableModel tb = (DefaultTableModel) this.tablaProductos.getModel();
            Producto objS= (Producto) tablaProductos.getValueAt(fila, 1);
            FacadeProducto objF = new FacadeProducto();
            objF.updateEstado(objS);
        }
    }
    private void cargartabla(){
        FacadeProducto objF = new FacadeProducto();
        List<Producto> lista = objF.ListarProductosInfo();
        DefaultTableModel tb = (DefaultTableModel) this.tablaProductos.getModel();
        tb.getDataVector().clear();
        tb.setColumnIdentifiers(new String[]{
            "id", "Nombre", "Dimension", "Material","Color","Tipo","Unidades Disponibles","Precio","Estado"});
        if (lista != null) {
            for (Producto i : lista) {
                    tb.addRow(new Object[]{i.getID_P(), i, i.getDimension(), i.getMaterial(),i.getColor(),i.getTipo()
                    , i.getCantidad(), i.getPrecio(), i.isEstado()});
            }
        }
    }
    private void cargartablaVendedor(){
        FacadeVendedor objF = new FacadeVendedor();
        List<Vendedor> lista = objF.ListarVendedor();
        DefaultTableModel tb = (DefaultTableModel) this.TablaVendedores.getModel();
        tb.getDataVector().clear();
        tb.setColumnIdentifiers(new String[]{
            "id", "Nombre", "Correo"});
        if (lista != null) {
            for (Vendedor i : lista) {
                    tb.addRow(new Object[]{i.getID(), i, i.getCorreo()});
            }
        }
    }
    public static boolean Email (String email) {

    // Establecer el patron
    Pattern p = null;
    p =Pattern.compile("[-\\w\\.]+@[\\.\\w]+\\.\\w+");

    // Asociar el string al patron
    Matcher m = null;
    m= p.matcher(email);
    
    if(m.find()){
        return true;
    }else{
        return false;
    }

   // Comprobar si encaja
}
    private boolean insertarProducto(Producto produc, Provedor prove){
        boolean res = false;
        FacadeProveedor proDAO = new FacadeProveedor();
        
        
        if(proDAO.CrearProveedor(prove)){
            res=proDAO.CrearTelefono(prove);
        }
        FacadeProducto produDAO = new FacadeProducto();
        if(produDAO.CrearProducto(produc)){
            res=produDAO.CrearColor(produc);
            res=produDAO.CrearMaterial(produc);
            res=produDAO.CrearTipo(produc);
        }
        if(res){
            res=produDAO.distribuye(produc, prove);
        }
        
        return res;
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDB1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Identificacion;
    private javax.swing.JTable TablaVendedores;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnDash;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarVendedor;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnIngresarProductos;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JPasswordField contraseña_V;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPasswordField pass_RV;
    private javax.swing.JPanel pnconfig;
    private javax.swing.JPanel pndash;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidadpro;
    private javax.swing.JTextField txtColorProduc;
    private javax.swing.JTextField txtContactoPro;
    private javax.swing.JTextField txtDimensionProduc;
    private javax.swing.JTextField txtDireccionPro;
    private javax.swing.JTextField txtIdentificacionPro;
    private javax.swing.JTextField txtMaterialProduc;
    private javax.swing.JTextField txtNombrePro;
    private javax.swing.JTextField txtNombreProduc;
    private javax.swing.JTextField txtNumeroRef;
    private javax.swing.JTextField txtPrecioProduc;
    private javax.swing.JTextField txtTelefonoPro;
    private javax.swing.JTextField txtTipoProduc;
    private javax.swing.JTextField txt_CorreoRV;
    private javax.swing.JTextField txt_IdentificacionRV;
    private javax.swing.JTextField txt_NombreRv1;
    private javax.swing.JTextField txt_NombreV;
    // End of variables declaration//GEN-END:variables
}
